#heat pump controller by hipik
#inspiration https://github.com/openhp/HeatPumpController/
#no EEV module yet/no need on my side, got TXV
#meant to be used standalone with HA as an option to visualize

#bugs: on restart it triggers all relays for a short time

#<<: !include secrets.yaml


esphome:

  name: esp-klima

  on_boot:
    priority: 700.0
      # ...
    then:
      - switch.turn_on: safety



esp8266:
  board: nodemcuv2


# Enable Home Assistant API
api:
  password: "dohled"
  reboot_timeout: 900s
ota:
  password: "dohled"

wifi:
  reboot_timeout: 900s
  power_save_mode: none
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  - ssid: !secret wifi_ssid3
    password: !secret wifi_password3


  # Enable fallback hotspot (captive portal) in case wifi connection fails

#mqtt_host: !secret mqtt_host

# Abbr.	Full name
#Tae	after evaporator
#Tbe	before evaporator
#Tci	cold side "input"
#Tco	cold side "output"
#Tbc	before condenser
#Tac	after condenser
#Thi	hot side "input"
#Tho	hot side "output"
#Tcrc	crankcase (compressor itself)
#The additional sensor used in "swimming pool heater" or "water tank heater" schemes, check SETPOINT_TS1 option:

#Abbr.	Full name
#Ts1	additional sensor1
#Additional sensors, disabled and not used by default:

#Abbr.	Full name
#Treg	regenerator temperature
#Ts2	additional sensor2
#Relays:

#Abbr.	Full name
#RCRCH	crankcase heater relay
#RC	cold side water pump relay
#RH	cold side water pump relay
#RP	heat pump (compressor) relay
#Other:

#Abbr.	Full name
#LSM	LastStopCause
#LSC	LastStartMessage
#CWP/CCP	cold side water (circulating) pump
#HWP/HCP	cold side water (circulating) pump
#EEVP	EEV position
#HP	heat pump


logger:
 # baud_rate: 0

#mqtt:
#  broker: !secret mqtt_host
 # id: mqtt_client
 # Example configuration entry
dallas:
  - pin: D7
    update_interval: 10s
    id: temps

#number:
#  - platform: template
#    name: "temp update frequency slider"
#    id: "Slider"
#    step: 1
#    min_value: 1
#    max_value: 100
#    mode: slider
#    set_action:
#    - logger.log: Slider
  #    then:
   #     - lambda:  id(temps) = x;

#Individual sensors

sensor:
  - platform: dallas
    address: 0x9bea5db81e64ff28
    name: "Outdoor after evaporator Tae"
    id: tae
#add temperature ranges
  - platform: dallas
    address: 0xd16840831e64ff28
    name: "Outdoor Unit before evaporator TBe"
    id: tbe
#add temperature ranges
  - platform: dallas
    address: 0x8ead46831e64ff28
    name: "Indoor Unit hot out tho"
    id: tho
    on_value_range:
        - above: 65.0
          then:
            - switch.turn_on: safety
            - logger.log: "tbc fail"
        - below: 5.0
          then:
            - switch.turn_off: safety
  - platform: dallas
    address: 0x536db7931e64ff28
    name: "Indoor Unit hot in thi"
    id: thi
    on_value_range:
        - above: 65.0
          then:
            - switch.turn_on: safety
            - logger.log: "tbi fail"
        - below: 5.0
          then:
            - switch.turn_off: safety
  - platform: dallas
    address: 0xba5cbe9f1e64ff28
    name: "Indoor before condenser tbc"
    id: tbc
    on_value_range:
        - above: 65.0
          then:
            - switch.turn_on: safety
            - logger.log: "tbc fail"
        - below: 50.0
          then:
            - switch.turn_off: safety
  - platform: dallas
    address: 0xda99c59f1e64ff28
    name: "Indoor after condenser tac"
    id: tac
    on_value_range:
        - above: 65.0
          then:
            - switch.turn_on: safety
            - logger.log: "tac fail"
        - below: 50.0
          then:
            - switch.turn_off: safety
  - platform: dallas
    address: 0xda99c59f1e64ff28
    name: "Outdoor compressor crankcase tcrc"
    id: tcrc
    on_value_range:
        - above: 5.0
          then:
            - switch.turn_off: crankcase
        - below: 5.0
          then:
            - switch.turn_on: crankcase
            - switch.turn_off: compressor
            - switch.turn_off: fan
            - switch.turn_off: four_wv
            - delay: 1 min
            - logger.log: "Heating crankcase"


#AC wiring: safety switch on AC input
#connect safety to AC in on all other relays
#in any situation, safety stops all AC action
#wire compressor external unit relay via HT pressure cut off valve to avoid overpressure.

button:
 - platform: template
   name: defrost
   on_press:
     then:
       - logger.log: "defrost Pressed"
       - switch.turn_off: four_wv
       - switch.turn_on: compressor
       - delay: 10 s
       - switch.turn_on: safety
       - delay: 1 s
       - switch.turn_off: safety



switch:
  - platform: gpio
    name: "Compressor"
    pin: D3
    id: compressor
    restore_mode: ALWAYS_OFF
    inverted: true
    interlock: crankcase
  - platform: gpio
    name: "Fan"
    pin: D2
    id: fan
    restore_mode: ALWAYS_OFF
    inverted: true
  - platform: gpio
    name: "Circulating pump"
    pin: D6
    restore_mode: ALWAYS_OFF
    inverted: true
    id: circulation
  - platform: gpio
    name: "Heat mode selector 4wv"
    pin: D4
    restore_mode: ALWAYS_OFF
    inverted: true
    id: four_wv
  - platform: gpio
    name: "Crank heater"
    pin: D8
    restore_mode: ALWAYS_OFF
    inverted: true
    id: crankcase
    interlock: compressor
  - platform: gpio
    name: "safety" #needs power to enable AC out
    pin: D5
    restore_mode: ALWAYS_OFF #safe mode on
    inverted: yes
    id: safety
    #restore_mode: RESTORE_DEFAULT_OFF
    on_turn_off:  #safety switch off - ready to go
      - switch.turn_off: fan
      - switch.turn_off: compressor
      - switch.turn_off: four_wv
      - logger.log: "Disarming safety - delay 10s"
      - switch.turn_off: circulation
      - climate.control:
          id: HP_Controller
          mode: "OFF"    #safety precaution
      - delay: 10 s
      - climate.control:
          id: HP_Controller
          mode: "HEAT"    #GO
    on_turn_on: #safety switch on - FAIL
      - logger.log: "Arming safety"
      - switch.turn_off: fan
      - switch.turn_off: compressor
      - switch.turn_off: four_wv
      - switch.turn_off: circulation
      - climate.control:
          id: HP_Controller
          mode: "OFF"


  - platform: restart
    name: "Klima ESP Restart"


# Example dual-point configuration entry
climate:
  - platform: bang_bang

    name: "HP_Controller"
    sensor: tho
    default_target_temperature_low: 30 °C
    default_target_temperature_high: 33 °C
    heat_action:

      - switch.turn_on: four_wv
      - delay: 1s
      - switch.turn_on: fan
      - delay: 1s

      - switch.turn_on: circulation
      - delay: 2s
      - switch.turn_on: compressor
      - logger.log: "Heating on"
    idle_action:
      - switch.turn_off: fan
      - switch.turn_off: compressor
      - switch.turn_off: four_wv
      - logger.log: "Heating off + delay 1min"
      - switch.turn_off: circulation
      - delay: 1 min

    visual:
      min_temperature: 18
      max_temperature: 60
    id: "HP_Controller"

web_server:
  port: 80
