#heat pump controller by hipik
#inspiration https://github.com/openhp/HeatPumpController/
#no EEV module yet/no need on my side, got TXV
#meant to be used standalone with HA as an option to visualize

#bugs: on restart it triggers all relays for a short time



#AC wiring: safety_stop switch on AC input
#connect safety_stop to AC in on all other relays
#in any situation, safety_stop stops all AC action
#wire compressor external unit relay via HT pressure cut off valve to avoid overpressure.


# Abbr.	Full name
#Tae	after evaporator
#Tbe	before evaporator
#Tci	cold side "input"
#Tco	cold side "output"
#Tbc	before condenser
#Tac	after condenser
#Thi	hot side "input"
#Tho	hot side "output"
#Tcrc	crankcase (compressor itself)
#The additional sensor used in "swimming pool heater" or "water tank heater" schemes, check SETPOINT_TS1 option:

#Abbr.	Full name
#Ts1	additional sensor1
#Additional sensors, disabled and not used by default:

#Abbr.	Full name
#Treg	regenerator temperature
#Ts2	additional sensor2
#Relays:

#Abbr.	Full name
#RCRCH	crankcase heater relay
#RC	cold side water pump relay
#RH	cold side water pump relay
#RP	heat pump (compressor) relay
#Other:

#Abbr.	Full name
#LSM	LastStopCause
#LSC	LastStartMessage
#CWP/CCP	cold side water (circulating) pump
#HWP/HCP	cold side water (circulating) pump
#EEVP	EEV position
#HP	heat pump


#<<: !include secrets.yaml


esphome:
  name: esp-klima
  on_boot:
    priority: 700.0
      # ...
    then:
      - switch.turn_on: safety_stop

esp8266:
  board: nodemcuv2


# Enable Home Assistant API
api:
  password: !secret apipass
  reboot_timeout: 900s

ota:
  password: !secret otapass

wifi:
  reboot_timeout: 900s
  power_save_mode: none
  networks:
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  - ssid: !secret wifi_ssid3
    password: !secret wifi_password3
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

logger:

#mqtt_host: !secret mqtt_host

#mqtt:
#  broker: !secret mqtt_host
 # id: mqtt_client
 # Example configuration entry

#temp sensors hub
dallas:
  - pin: D7
    update_interval: 10s
    id: temps

#Individual sensors

sensor:
  - platform: dallas
    address: 0x9bea5db81e64ff28
    name: "HP Outdoor after evaporator - Tae"
    id: tae
#add temperature ranges
  - platform: dallas
    address: 0xd16840831e64ff28
    name: "HP Outdoor Unit before evaporator - Tbe"
    id: tbe
#add temperature ranges
  - platform: dallas
    address: 0x8ead46831e64ff28
    name: "HP Indoor Unit hot out - Tho"
    id: tho
    on_value_range:
        - above: 65.0
          then:
            - switch.turn_on: safety_stop
            - logger.log: "tbc fail"
       # - below: 5.0
        #  then:
         #   - switch.turn_off: safety_stop
  - platform: dallas
    address: 0x5287879f1e64ff28
    name: "HP Indoor Unit Hot In - Thi"
    id: thi
    on_value_range:
        - above: 65.0
          then:
            - switch.turn_on: safety_stop
            - logger.log: "tbi fail"
       # - below: 5.0
        #  then:
         #   - switch.turn_off: safety_stop
  - platform: dallas
    address: 0xba5cbe9f1e64ff28
    name: "HP Indoor before condenser - Tbc"
    id: tbc
    on_value_range:
        - above: 65.0
          then:
            - switch.turn_on: safety_stop
            - logger.log: "tbc fail"
       # - below: 50.0
        #  then:
         #   - switch.turn_off: safety_stop
  - platform: dallas
    address: 0x536db7931e64ff28
    name: "HP Indoor after condenser - Tac"
    id: tac
    on_value_range:
        - above: 65.0
          then:
            - switch.turn_on: safety_stop
            - logger.log: "tac fail"
       # - below: 50.0
        #  then:
         #   - switch.turn_off: safety_stop

  - platform: dallas
    address: 0xda99c59f1e64ff28
    name: "HP Outdoor Compressor temp - Tcc"
    id: tcrc
    on_value_range:
        - above: 5.0
          then:
          #  - switch.turn_off: crankcase
        - below: 5.0
          then:
            - switch.turn_on: safety_stop
          #  - switch.turn_on: crankcase
            - switch.turn_off: compressor
            - switch.turn_off: fan
            - switch.turn_off: four_wv
            - delay: 1 min
            - logger.log: "Heating crankcase - safety armed"

#i2c:
#  sda: D8
#  scl: D6

#font:
# - file: 'config/slkscr.ttf'
#   id: font1
#   size: 8

#display:
#  - platform: ssd1306_i2c
#    model: "SSD1306 128x64"
#    reset_pin: D0
#    address: 0x3C
#    lambda: |-
#      it.print(0, 0, id(font1), "Hello World!");

button:
 - platform: template
   name: defrost
   on_press:
     then:
       - logger.log: "defrost Pressed"
       - switch.turn_off: four_wv
       - switch.turn_on: compressor
       - delay: 30 s
       - switch.turn_on: safety_stop
       - delay: 1 s
       - switch.turn_off: safety_stop

switch:
  - platform: gpio
    name: "HP Compressor"
    pin: D3
    id: compressor
    restore_mode: ALWAYS_OFF
    inverted: true

  - platform: gpio
    name: "HP Fan"
    pin: D2
    id: fan
    restore_mode: ALWAYS_OFF
    inverted: true
#  - platform: gpio
  #  name: "HP Circulating pump"
 #   pin: D6
   # restore_mode: ALWAYS_OFF
   # inverted: true
  #  id: circulation
  - platform: gpio
    name: "HP Heat mode selector 4wv" #on: heat, off: cool
    pin: D4
    restore_mode: ALWAYS_OFF
    inverted: true
    id: four_wv
 ## - platform: gpio
 #   name: "HP Crank heater"
 #   pin: D8
 #   restore_mode: ALWAYS_OFF
 #   inverted: true
 #   id: crankcase
 #   interlock: compressor


#safety stop
#noninverted -> meant to shutdown all AC inputs if LOW

  - platform: gpio
    name: "HP safety_stop" #needs power to enable AC out , disables all HV stuff
    pin: D5
    restore_mode: ALWAYS_ON #safe mode on
    inverted: yes
    id: safety_stop
    #restore_mode: RESTORE_DEFAULT_ON

    on_turn_on: #safety_stop switch on - FAIL
      - logger.log: "Arming safety_stop"

      - switch.turn_off: compressor
      - switch.turn_off: fan
      - switch.turn_off: four_wv
   #   - switch.turn_off: circulation
      - climate.control:
          id: HP_Controller
          mode: "OFF"

    on_turn_off:  #safety_stop switch off - ready to go
      - switch.turn_off: fan
      - switch.turn_off: compressor
      - switch.turn_off: four_wv
      - logger.log: "Disarming safety_stop - delay 10s"
    #  - switch.turn_off: circulation
      - climate.control:
          id: HP_Controller
          mode: "OFF"    #safety_stop precaution
      - delay: 10 s
      - climate.control:
          id: HP_Controller
          mode: "HEAT"    #GO

  - platform: restart
    name: "HP Controller Restart"

# controller

climate:
  - platform: bang_bang

    name: "HP_Controller"
    sensor: tho
    default_target_temperature_low: 30 °C
    default_target_temperature_high: 35 °C
    heat_action:

      - switch.turn_on: four_wv
      - logger.log: "4WV ON"
      - delay: 1s


     # - delay: 3s
     # - switch.turn_on: circulation
      #- delay: 2s
      - switch.turn_on: compressor
      - logger.log: "CP ON"
      - delay: 3s
      - switch.turn_on: fan
      - logger.log: "FAN ON"

    idle_action:
      - switch.turn_off: fan
      - switch.turn_off: compressor
      - switch.turn_off: four_wv
      - logger.log: "IDLE: ALL off + delay 1min"
     # - switch.turn_off: circulation
      - delay: 1 min

    visual:
      min_temperature: 18
      max_temperature: 50
    id: "HP_Controller"

web_server:
  port: 80
